Repository nettee-space/nettee-kanban, pull requests merged in 2025-08, with the labels that each got.

#59 ✨사이드바 수퍼베이스 데이터 연동
  .env.local
  src/features/kanban/components/Sidebar/AssigneeFilter.tsx
  src/features/kanban/components/Sidebar/LabelFilter.tsx
  src/features/kanban/components/Sidebar/ProjectFilter.tsx
  src/features/kanban/components/Sidebar/TeamFilter.tsx
  src/features/kanban/constants/kanban.ts
  src/features/kanban/hooks/useKanbanData.ts
  src/shared/lib/supa-client.ts
Labels: type: feature

#65 label을 shadcn 기반으로 변경 및 선택 시 ID를 반환하도록 수정
  src/features/kanban/components/Modal/KanbanModal.tsx
  src/features/kanban/components/Sidebar/LabelFilter.tsx
  src/features/kanban/constants/kanban.ts
  src/features/kanban/store/filterStore.ts
  src/shared/components/ui/checkbox.tsx
  src/shared/components/ui/label.tsx
Labels: type: refactor, status: done

#68 ✨ 칸반 내 드래그 앤 드랍 기능 구현
  .env.local
  mise.toml
  src/app/index.tsx
  src/features/kanban/components/KanbanBoard/Column/DropIndicator.tsx
  src/features/kanban/components/KanbanBoard/Column/KanbanCard.tsx
  src/features/kanban/components/KanbanBoard/Column/KanbanColumn.tsx
  src/features/kanban/components/KanbanBoard/ProjectHeader.tsx
  src/features/kanban/components/KanbanBoard/ProjectKanban.tsx
  src/features/kanban/components/KanbanBoard/Team/ColumnContainer.tsx
  src/features/kanban/components/KanbanBoard/Team/TeamBoard.tsx
  src/features/kanban/components/KanbanBoard/Team/TeamHeader.tsx
  src/features/kanban/components/KanbanBoard/index.tsx
  src/features/kanban/components/Modal/KanbanModal.tsx
  src/features/kanban/components/Sidebar/AssigneeFilter.tsx
  src/features/kanban/components/Sidebar/LabelFilter.tsx
  src/features/kanban/components/Sidebar/ProjectFilter.tsx
  src/features/kanban/components/Sidebar/index.tsx
  src/features/kanban/components/layout/NetteeKanbanLayout.tsx
  src/features/kanban/constants/kanban.ts
  src/features/kanban/constants/nettee.ts
  src/features/kanban/hooks/useDragAndDrop.ts
  src/features/kanban/hooks/useKanbanData.ts
  src/features/kanban/store/filterStore.ts
  src/features/kanban/types/issues.ts
  src/shared/components/ui/divider.tsx
  src/store/issueStore.ts
Labels: type: refactor, type: feature, status: in-progress

#71 사이드바의 accordion들을 shadcn의 accordion으로 변경
  package.json
  pnpm-lock.yaml
  src/features/kanban/components/KanbanBoard/Column/KanbanCard.tsx
  src/features/kanban/components/KanbanBoard/Column/KanbanColumn.tsx
  src/features/kanban/components/KanbanBoard/ProjectKanban.tsx
  src/features/kanban/components/KanbanBoard/Team/ColumnContainer.tsx
  src/features/kanban/components/KanbanBoard/Team/TeamBoard.tsx
  src/features/kanban/components/Sidebar/AssigneeFilter.tsx
  src/features/kanban/components/Sidebar/LabelFilter.tsx
  src/features/kanban/components/Sidebar/ProjectFilter.tsx
  src/features/kanban/components/Sidebar/TeamFilter.tsx
  src/features/kanban/components/Sidebar/ViewOptions.tsx
  src/features/kanban/components/Sidebar/index.tsx
  src/features/kanban/hooks/useDragAndDrop.ts
  src/features/kanban/hooks/useKanbanData.ts
  src/features/kanban/store/filterStore.ts
  src/shared/components/ui/accordion.tsx
  src/store/issueStore.ts
Labels: type: refactor, status: done
